# Generated by Django 5.0 on 2025-02-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
    ]
